# Generated by Django 4.2.2 on 2023-06-26 19:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_worklow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequestElevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator_review', to='elevator_worklow.elevator')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_review', to='elevator_worklow.request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
